version: "2.2"
services:
  fleet:
    container_name: fleet
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    ports:
      - 8220:8220
    user: root
    environment:
      - ELASTICSEARCH_HOST=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_CA=/etc/pki/tls/certs/ca/ca.crt
      - KIBANA_HOST=https://kibana:5601
      - KIBANA_USERNAME=elastic
      - KIBANA_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_CA=/etc/pki/tls/certs/ca/ca.crt
      - KIBANA_FLEET_SETUP=1
      - KIBANA_FLEET_HOST=https://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_FLEET_CA=/etc/pki/tls/certs/ca/ca.crt
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://elasticsearch:9200
      - FLEET_SERVER_ELASTICSEARCH_CA=/etc/pki/tls/certs/ca/ca.crt
      - FLEET_SERVER_ES_CA=/etc/pki/tls/certs/ca/ca.crt
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_TOKEN_POLICY_NAME=Default
      - FLEET_SERVER_HOST=0.0.0.0
      - FLEET_SERVER_PORT=8220
      - FLEET_SERVER_CERT=/etc/pki/tls/certs/fleet/fleet.crt
      - FLEET_SERVER_CERT_KEY=/etc/pki/tls/certs/fleet/fleet.key
      - FLEET_SERVER_INSECURE_HTTP=false
      - FLEET_ENROLL=1
      - FLEET_URL=https://fleet:8220
      - FLEET_CA=/etc/pki/tls/certs/ca/ca.crt
      - SSL_CERTIFICATE_AUTHORITIES=/etc/pki/tls/certs/ca/ca.crt
      - ELASTIC_AGENT_TAGS="auto-fleet-server"
    volumes:
      - certs:/etc/pki/tls/certs
volumes:
  certs:
    driver: local

